### ISSUE TITLE
conso_sensor: Evaluate the power consumption

### ISSUE THREAD

**Issue by da-ekchajzer** [Boavizta/Energizta#2]
# Problem

For each workload, we need to collect the power consumption of the components or the machine.

# Solution

We need to take into account multiple sources of consumption data to address the maximum architecture and compare the data sources between them. 

* RAPL
* IMPI
* MANUAL

This feature should be done in boagent. See : https://github.com/Boavizta/boagent/issues/35

# Informations
## RAPL
We can either access directly to RAPL API (https://web.eece.maine.edu/~vweaver/projects/rapl/) or access it through another software such as scaphandre (https://github.com/hubblo-org/scaphandre)

### Intel
For RAM and CPU, we can use RAPL  

### AMD
According to @bpetit, RAPL should work for AMD x86, with Linux core 5.11 or higher

### ARM
Discussion in progress https://github.com/hubblo-org/scaphandre/issues/35

### RAM
Discussion in progress https://github.com/hubblo-org/scaphandre/issues/35

## IPMI
Access the electrical evaluation through the IPMI API. 
https://en.wikipedia.org/wiki/Intelligent_Platform_Management_Interface

## Manual
User should be able to provide the power consumption manually when they use a power sensor that is not implemented in Energizta (with external wattmeter for instance).

@bpetit I would be interested to have your opinion on that and maybe link it with ongoing issues in scaphandre

**Comment by bpetit** [comment]
We should have a look to https://github.com/green-coding-berlin/tools and synchronize with green coding
